services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # Mapping seed.sql to the auto-initialization folder
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      # Persisting data locally
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: